--minetest.register_alias("default:stone","blocks:stone")
--minetest.register_alias("default:desert_stone","blocks:desert_stone")
--minetest.register_alias("default:stonebrick","blocks:stonebrick")
--minetest.register_alias("default:desert_stonebrick","blocks:desert_stonebrick")
--minetest.register_alias("default:sandstone","blocks:sandstone")
--minetest.register_alias("default:sandstonebrick","blocks:sandstonebrick")
--minetest.register_alias("default:brick","blocks:brick")
--minetest.register_alias("default:glass","blocks:glass")
minetest.register_alias("default:obsidian_glass","blocks:obsidian_glass")
minetest.register_alias("default:obsidian","blocks:obsidian")
minetest.register_alias("default:stick","group:stick")
minetest.register_alias("ores:chromium","ores:aluminium")
minetest.register_alias("ores:tin","ores:titan")
minetest.register_alias("group:wood","group:planks")
minetest.register_alias("default:sandstone", "blocks:sandstone")

-- fixes know errors in mapgenv6
minetest.register_alias("default:cobble_node", "air")

-- fixes for deleted plank
minetest.register_alias("trees:ash_plank","blocks:ash_planks")
minetest.register_alias("trees:aspen_plank","blocks:aspen_planks")
minetest.register_alias("trees:birch_plank","blocks:birch_planks")
minetest.register_alias("trees:chestnut_plank","blocks:chestnut_planks")
minetest.register_alias("trees:maple_plank","blocks:maple_planks")
minetest.register_alias("trees:pine_plank","blocks:pine_planks")
minetest.register_alias("trees:sequoia_plank","blocks:sequoia_planks")
minetest.register_alias("trees:spruce_plank","blocks:spruce_planks")
